### ISSUE TITLE
Background messages not working with firebase

### ISSUE THREAD

**Issue by xxparthparekhxx** [P-yiush07/background-sms#1]
Package Version: flutter_background_messenger: ^0.0.2

Flutter/Dart Version: Flutter 3.24.5

Android Version: Android 15

Issue Description: 
I have created a app to get messages from firebase messaging and sending a sms from the device to anyone the server wants the only problem is when i get the firebaseMessage in the background the function runs but the sms is not being sent 

Steps To Reproduce:
create flutter x firebase project with messageing 
add your send message function in the callback function 
manually send the message in the background 

``` dart
@pragma('vm:entry-point')
Future<void> _backgroundMessageHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  final messenger = FlutterBackgroundMessenger();
  print("sending message")
  await messenger.sendSMS(
    message: message.data['message'],
    phoneNumber: message.data['recipient'],
  );
  print("message sent")
}
``` 

Expected Behavior:
message should be sent in the background as the name of the library suggests 

Actual Behavior:
No sms is being sent 

Error Message:
No error message just nothing from the library but just the print messages from my code 

check out the [Project](https://github.com/xxparthparekhxx/sms-service)

**Comment by P-yiush07** [comment]
Hey @xxparthparekhxx , 
Have you tried sending sms first by trying it on any number with a message in it? 
Kindly check that first and let me know that its working or not.  I have to make sure first its working on Android 15 or not😊

You can create a temporary send button for testing this thing, and on click of that send button use the package to send any message to any number as mentioned in the doc. Then let me know it worked or not.

Thanks

**Comment by xxparthparekhxx** [comment]
Yes foreground messages work when the app is open I am able to send messages but when the app is in the background it doesn't work

**Comment by P-yiush07** [comment]
> Yes foreground messages work when the app is open I am able to send messages but when the app is in the background it doesn't work

While sending SMS your main app is not opened its in background ?
And when the app is opened in Foreground, package is sending sms correctly ?

right?

**Comment by P-yiush07** [comment]
@xxparthparekhxx from my end theres no issue, i tested the package the messaegs are getting sent in background, i suggest you to put the code in try and catch, and then tell me the behaviour.

like this

```
@pragma('vm:entry-point')
Future<void> _backgroundMessageHandler(RemoteMessage message) async {
  // Initialize Firebase first
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform
  );
  
  // Create messenger instance
  final messenger = FlutterBackgroundMessenger();
  
  try {
    // Add error handling and logging
    if (message.data.containsKey('recipient') && message.data.containsKey('message')) {
      final success = await messenger.sendSMS(
        phoneNumber: message.data['recipient'],
        message: message.data['message'],
      );
      
      print('Background SMS send result: $success');
    } else {
      print('Missing required SMS data in background message');
    }
  } catch (e) {
    print('Error sending background SMS: $e');
  }
}
```

Also check your AndroidManifest.xml to inlcude these permissions:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.SEND_SMS"/>
    <uses-permission android:name="android.permission.READ_SMS"/>
    <uses-permission android:name="android.permission.RECEIVE_SMS"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
</manifest>
```

Make sure your Firebase message payload is correctly formatted as:

```
{
  "data": {
    "recipient": "+1234567890",
    "message": "Your SMS message here"
  }
}
```

and also dont forget to take permissions from user

**Comment by rifathasanpriyo** [comment]
Can my app continue to send SMS in the background even if it is closed?

**Comment by P-yiush07** [comment]
> Can my app continue to send SMS in the background even if it is closed?

By the word "Closed", if it means closing the whole app by removing it from the recents apps, then it will not work in the current version (if possible can add later in next version),  and if you just minimize it by keeping it in the background then it will definitely work.
